### ISSUE TITLE
error when load initial word embedding

### ISSUE THREAD

**Issue by yaoing** [LHRYANG/CRL_EGPG#2]
Hello, I have downloaded the `glove.6B.300d.txt` file from official website and load the glove model successfully. However, the vocabulary dim seem not match enough, is there a mini version of `glove.6B.300d.txt` ?

![image](https://user-images.githubusercontent.com/19516208/137459535-f4037c8b-111e-4cd8-8fde-178483e19f61.png)

**Comment by LHRYANG** [comment]
QQP and PARANMT have different vocabulary size. You can manually modify the size according to the dataset.
One is 23922, the other is 57757. 

Modify the path to corresponding word2idx file in initialise_word_embedding()...

**with open("./data2/word2idx.pkl",'rb') as f:**
